### ISSUE TITLE
Reconnecting to the dev server causes high ping, the graph to lag, weird connection issues and error on the server

### ISSUE THREAD

**Issue by Glubs9** [ANU-Rocketry/control-panel#16]
after connecting to the server, deleting the ip in the text box and retyping it back in (deleting the ip using backspace, one letter at a time seems necessary). The ping gets really high (usually above 200, highest I found was 24,000), the graph starts to lag and an error appears on the server.

Additionally, I discovered this while writing the connection status indicator and the connection status (socket.readyState) behaves very strangely. I have not found a pattern for what happens but it may hint at the underlying issue.

**Comment by OliverBalfour** [comment]
Fixed on the new branch
