### ISSUE TITLE
Better UPS status

### ISSUE THREAD

**Issue by OliverBalfour** [ANU-Rocketry/control-panel#3]
We've got a universal power supply (UPS) that our RPi etc plugs into so that if the generator power cuts, we can still run on battery long enough to solve the problem.

We have an indicator on the frontend to warn operators when it's running on battery charge and might cut out soon. At the moment it just prints a Python enum and looks like this:

<img width="223" alt="image" src="https://user-images.githubusercontent.com/11626018/174470284-59cd4fdc-3905-45ed-832d-515e02b2d577.png">

What we really want is
* A green tick/intense red cross/grey question mark icon (careful of colourblindness issues) next to the status
* A snackbar notification when the status changes that is hard to miss, must be manually dismisssed, but doesn't obscure any UI elements, and
* The status should not be written in all caps

This isn't a rigid set of requirements, but any solution to this ticket should make status changes more obvious 

The snackbar when power is lost should probably warn the operator to depressurise the system safely before the UPS battery runs out

**Comment by Glubs9** [comment]
Do you have a mechanism already set up for testing different UPS statuses? like something on the dev server?

**Comment by OliverBalfour** [comment]
Ohh, good point! We don't have this, no!

So there's a command we use, `apcaccess status`, and we grep the output for the right string. This means if you plug your computer into a UPS with a USB-B cable it'll work (ie take the UPS and USB A to B cables from the green box in Ian Ross, plug USB A into your laptop, USB B into the side of the UPS, plug UPS into the wall, don't bother powering anything with the UPS power points), so you might have to test this on campus and find a way into that room. I'm happy to help with this when I'm out of isolation.

You could also do some preliminary work by temporarily hardcoding `src/server.py` to return something of your choosing in `get_UPS_status`.

**Comment by Glubs9** [comment]
when do you get out of isolation?

**Comment by OliverBalfour** [comment]
Thursday

**Comment by Glubs9** [comment]
do you mind if I use this library for snackbars? https://mui.com/material-ui/react-snackbar/
It looks fairly good

if not, it doesn't seem that hard to make custom

**Comment by OliverBalfour** [comment]
yep that's okay
